#!/bin/bash

function dotfiles
{
    cd "$HOME/dotfiles" || exit;
}

function temp
{
    cd "$HOME/temp" || exit ; 
}

function conf
{
  cd "$HOME/.config" || exit ;
}

function adrian
{
  cd '/mnt/c/users/Adrian' || exit;
}

function projects
{ cd '/home/adrian/Documents/Projects' || exit; } 

function exercises
{
  cd "$HOME/Dropbox/vimwiki/Exercise" || echo Error!;
}

function vimtutor
{
  nvim +Tutor ;
}

function vimhelp
{
  nvim +"help | only";
}

function vimtoc
{
  #Vim Table of Contents
  nvim +"help reference_toc | only";
}

function music
{
  cd "$HOME/Music" || exit
}

function PdfOpen
{
 if [[ ! "$1" =~ \.pdf$ ]]; then
        echo "Error: The first argument is not a PDF file."
        return 1
    fi

    (~/Applications/pdf/Sioyek-x86_64.AppImage "$1" &) &>/dev/null 2>&1 
}

function WikiIndex
{
cd ~/vimwiki/ || exit ;
nvim ~/vimwiki/100_Index.md ;
}

function documents
{ 
  cd ~/Documents || exit;
}

function downloads
{ cd ~/Downloads || exit;
}

function pictures
{
  cd ~/Pictures || exit
}

function cgrep
{
  grep --color=always; 
}
 
function cls
{
  clear; 
}
 
function vim
{
    if [ ! "$#" -gt 0 ]; then nvim $# ; fi ;
    if [ ! "$#" -eq 0 ]; then nvim; fi;
}
 
function bin
{
  cd ~/bin || exit; 
}

function youtube
{
  xdg-open youtube.com </dev/null &>/dev/null &
}

function editor
{
  nvim;
}
 
function home
{
  cd ~ || exit;
}
 
function clip
{ 
  xclip -selection c;
} #For pasting with Ctrl-v

function vimrc
{
  nvim ~/.vimrc;
}

function tmuxrc
{ nvim ~/.config/tmux/tmux.conf ; }

function tmuxstart
{
if [[ $# -eq 0 ]]; then
  result="$(sesh list | fzf)" ;
  sesh connect $result
else
  result="$HOME/$1"
  sesh connect "$result"
fi
tmux attach-session # "$result"
tmux attach
}

 tm() {
   [[ -n "$TMUX" ]] && change="switch-client" || change="attach-session"
   if [ "$1" ]; then 
      tmux "$change" -t "$1" 2>/dev/null || (tmux new-session -d -s "$1" && tmux "$change" -t "$1"); return
   fi
   session=$(tmux list-sessions -F "#{session_name}" 2>/dev/null | fzf --exit-0) &&  tmux $change -t "$session" || echo "No sessions found." & result="$(sesh list | fzf)" ;
  sesh connect "$result"
 }


#tmuxstart() {

#name=${PWD##*/}
#    tmux ls | grep "$name" && { tmux a -t "$name"; return 0; }
#    #rest of tmux script to create session named "sess"
#    tmux a -t "$name"
#}


function bashrc
{ nvim ~/.bashrc;}

function plugins
{ cd ~/.config/nvim/Plugins ||  exit; }

function rebash
{
 source "$HOME/dotfiles/.bashrc" && echo ".bashrc sourced!"
}

function BashkeyBindings
{
  less ~/.bashrc | grep \"^[^;]\"  | grep -v keybindings | grep -i bind;
}
 
function jan
{ cal -m 01;}
 
function feb
{ cal -m 02;}
 
function mar
{ cal -m 03;}
 
function apr
{ cal -m 04;}
 
function may
{ cal -m 05;}
 
function jun
{ cal -m 06;}
 
function jul
{ cal -m 07;}
 
function aug
{ cal -m 08;}
 
function sep
{ cal -m 09;}
 
function oct
{ cal -m 10;}
 
function nov
{ cal -m 11;}
 
function dec 
{ cal -m 12;}
