#!/bin/bash

function todo
{
  cd ~/vimwiki
  vim -c 'noautocmd vimgrep /#todo/j *.md | cope' 
}

function music
{
  cd ~/Music;

}

function pdf
{
  ~/.config/pdf/Sioyek-x86_64.AppImage  </dev/null &>/dev/null & 
}

function wiki 
{
  cd ~/vimwiki/ ; nvim  ~/vimwiki/100_Index.md ;
}
 
function vimwiki
 { cd ~/vimwiki; nvim ~/vimwiki/100_Index.md;}

function databases
{ cd ~/Documents/Programming/Databases; }

function documents
{ cd ~/Documents;}

function downloads
{ cd ~/Downloads; }

function pictures
{ cd ~/Pictures; }

function cgrep
{ grep --color=always; }
 
 
function cls
{  clear; }
 
function vim
{
    if [ ! "$#" -gt 0 ]; then nvim $# ; fi ;
    if [ ! "$#" -eq 0 ]; then nvim; fi;
    
}
 
function bin
{ cd ~/bin; }
 
function lichess
{ xdg-open lichess.org </dev/null &>/dev/null &}

function youtube
{ xdg-open youtube.com </dev/null &>/dev/null &}

function surfline
{ xdg-open surfline.com </dev/null &>/dev/null &}
 
function redreef
{ xdg-open https://video-monitoring.com/beachcams/boca/ </dev/null &>/dev/null &   }

function forecast
{ brave-browser https://www.swellinfo.com/surf-forecast/palm-beach-florida https://www.surf-forecast.com/breaks/Boynton-Beach </dev/null &>/dev/null &}
 
function chess
{ cd ~/vimwiki; nvim ~/vimwiki/chess.md;}

function editor
{ nvim;}
 
function home
{ cd ~;}
 
function clip
{ xclip -selection c;} #For pasting with Ctrl-v

function vimrc
{ nvim ~/.vimrc;}
 
function bashrc
{ nvim ~/.bashrc;}
 
function sbashrc
{ source ~/.bashrc;}

function bashkeybindings
{  cat ~/.bashrc | grep \"^[^;]\"  | grep -v keybindings | grep -i bind;}
 
function jan
{ cal -m 01;}
 
function feb
{ cal -m 02;}
 
function mar
{ cal -m 03;}
 
function apr
{ cal -m 04;}
 
function may
{ cal -m 05;}
 
function jun
{ cal -m 06;}
 
function jul
{ cal -m 07;}
 
function aug
{ cal -m 08;}
 
function sep
{ cal -m 09;}
 
function oct
{ cal -m 10;}
 
function nov
{ cal -m 11;}
 
function dec 
{ cal -m 12;}
