#!/bin/bash

function projects
{ cd '/home/adrian/Documents/Projects' || exit; } 

function exercises
{
  cd "$HOME/Dropbox/vimwiki/Exercise" || echo Error!;
}

function vimtutor
{
  nvim +Tutor ;
}

function vimhelp
{
  nvim +"help | only";
}

function vimtoc
{
  #Vim Table of Contents
  nvim +"help reference_toc | only";
}

function todo
{
  cd ~/vimwiki || exit
  vim -c 'noautocmd vimgrep /#todo/j *.md | cope' 
}

function music
{
  cd ~/Music || exit

}



function openpdf
{
 if [[ ! "$1" =~ \.pdf$ ]]; then
        echo "Error: The first argument is not a PDF file."
        return 1
    fi

    (~/Applications/pdf/Sioyek-x86_64.AppImage "$1" &) &>/dev/null 2>&1 

}

function index
{
cd ~/vimwiki/ || exit ;
nvim ~/vimwiki/100_Index.md ;
}

function wiki 
{
  cd ~/vimwiki/ || exit; 
  nvim  ~/vimwiki/100_Index.md ;
}
 
function vimwiki
 { cd ~/vimwiki || exit; 
   nvim ~/vimwiki/100_Index.md;
 }




function documents
{ 
  cd ~/Documents || exit;
}

function downloads
{ cd ~/Downloads || exit;
}

function pictures
{
  cd ~/Pictures || exit
}

function cgrep
{
  grep --color=always; 
}
 
 
function cls
{
  clear; 
}
 
function vim
{
    if [ ! "$#" -gt 0 ]; then nvim $# ; fi ;
    if [ ! "$#" -eq 0 ]; then nvim; fi;
}
 
function bin
{
  cd ~/bin || exit; 
}
 


function youtube
{
  xdg-open youtube.com </dev/null &>/dev/null &
}

 


function editor
{
  nvim;
}
 
function home
{
  cd ~ || exit;
}
 
function clip
{ 
  xclip -selection c;
} #For pasting with Ctrl-v

function vimrc
{
  nvim ~/.vimrc;
}
 
function bashrc
{ nvim ~/.bashrc;}
 
function rebash
{
 source $HOME/dotfiles/.bashrc && echo ".bashrc sourced!"
}

function bashkeybindings
{
  less ~/.bashrc | grep \"^[^;]\"  | grep -v keybindings | grep -i bind;
}
 
function jan
{ cal -m 01;}
 
function feb
{ cal -m 02;}
 
function mar
{ cal -m 03;}
 
function apr
{ cal -m 04;}
 
function may
{ cal -m 05;}
 
function jun
{ cal -m 06;}
 
function jul
{ cal -m 07;}
 
function aug
{ cal -m 08;}
 
function sep
{ cal -m 09;}
 
function oct
{ cal -m 10;}
 
function nov
{ cal -m 11;}
 
function dec 
{ cal -m 12;}
