#!/bin/bash



function screensaver
{
xscreensaver -no-splash &
  xscreensaver-command -activate;
}



function wallpaper
{
  find ~/.config/variety/Downloaded/Unsplash | fzf --preview="feh --bg-scale ~/.config/variety/Downloaded/Unsplash/{}" | 
    xargs -I {} feh --bg-scale ~/.config/variety/Downloaded/Unsplash/{}
}


function getTodaypictures
{
  # Gets pictures created today in Pictures folder
cd ~/Pictures || exit
current_date=$(date +'%Y%m%d')
for file in $(ls -1 | grep "^${current_date}_")
do
echo "$file"
done
}





