#!/bin/bash

function getcrypto 
{ 
  sudo snap run cointop; 
}

function getpaydates
{

powershell -c get-paydates

}

function get401k
{
  cd /home/adrian/Dropbox/vimwiki/Files || exit
  powershell -c import-csv 401k.csv;
}

function getamortization
{
  powershell -c get-amortization

}

function getamortization2
{
  powershell -c get-amortization2
}

function getbills
{
powershell -c get-bills

# powershell -c "import-csv ~/vimwiki/Files/bills.csv | select-object Bill, @{Name='Amount';E={\"{0,10:F2}\" -f $_.Bill}}, Due, Interest, Notes, Previous| sort-object -Descending Due | ft -autosize"
}

function openbills
{
  xdg-open ~/vimwiki/Files/bills.csv;
}
function updatebills
{
  powershell -c "set-bills";
}

alias getpaycheck="getpaydates"
