#!/bin/bash

function NetworkRouterIp
{
 netstat -r -n | awk '{print $2}' | head -n 3 | tail -n 2 ;
}


function NetworkIp
{
 echo IP Address
 hostname -I | awk '{print $1}'
}
alias getip=NetworkIp
function NetworkRouter
{
 routerip=$(getrouterip | tail -n 1 );
 xdg-open http://$routerip/ </dev/null &>/dev/null &

 echo $routerip
}
