#!/bin/bash
# lf integration
 lf () {
 	LF_TEMPDIR="$(mktemp -d -t lf-tempdir-XXXXXX)"
 	LF_TEMPDIR="$LF_TEMPDIR" lf-run -last-dir-path="$LF_TEMPDIR/lastdir" "$@"
 	if [ "$(cat "$LF_TEMPDIR/cdtolastdir" 2>/dev/null)" = "1" ]; then
 		cd "$(cat "$LF_TEMPDIR/lastdir")"
 	fi
 	rm -r "$LF_TEMPDIR"
 	unset LF_TEMPDIR
}

function getinstalledprograms
{
    aptitude search '~i!~M' 
}

function startdalai
{
  npx dalai serve;
}

function getdefaultprograms
{ bat /usr/share/applications/defaults.list; }

function getprograms
{
case "$(printf "Guake\nKeePass\nDropBox\nObsidian\n" | dmenu -l 10 -i -p "Programs:")" in
  "Guake") (guake &) &>/dev/null 2>&1 ;;
  "KeePass") (keepass2 &)  &>/dev/null 2>&1 ;;
  "DropBox") (flatpak run com.dropbox.Client &) &>/dev/null 2>&1 ;;
  "Obsidian") flatpak run md.obsidian.Obsidian &>/dev/null 2>&1 ;;
  *) exit 1 ;;
esac
}

function addnewsboaturl
{
  vim $HOME/snap/newsboat/6660/.newsboat/urls;
}

function startguake
{
 (guake &) &>/dev/null 2>&1 
}

function start
{
  (xdg-open . &)  &>/dev/null 2>&1
}

function keepass
{
  (keepass2 &)  &>/dev/null 2>&1 
}

function dropbox
{
  (flatpak run com.dropbox.Client &) &>/dev/null 2>&1
}

function zath
 {
   zathura $1 -P $2
 }


function obsidian
 {

   ( /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=obsidian.sh --file-forwarding md.obsidian.Obsidian @@u %u @@ </dev/null &>/dev/null & )
  
 }

function programs
{
dmenu_run -i -l 20;
}


