#!/bin/bash

function getbackgroundlocation
{
  gsettings get org.gnome.desktop.background picture-uri;
}

function getbook
{

brave-browser "? -inurl:htm -inurl:html -inurl:php intitle:'index of' (pdf|epub) \"$1\""  </dev/null &>/dev/null &
}

function brave
{
  xdg-open brave-browser &>/dev/null &
}

function rebrave
{
  pkill brave & 
  sleep 2
  xdg-open brave-browser &>/dev/null &
}


alias getwallpaperlocation="getbackgroundlocation"

function getwallpapers
{
  # open in kitty to and get icon preview for each
  find ~/.config/variety/Downloaded/Unsplash | fzf ;
}

function setwallpaper
{

# pausetime between iterations
sleeptime=900
# location of wallpapers folder
location="/home/adrian/.config/variety/Downloaded/Unsplash"

# ////////////////////////////////////////
# For random wallpaper selection
#array=($(ls $location*)) # populate array with directory contents
#( IFS=$'\n'; echo "${array[*]}" ) # list array content for debug
#size=${#array[@]}
#index=$(($RANDOM % $size))
#wallpaper=${array[$index]} # randomly select

wallpaper=$(ls $location | fzf)


#echo " SELECTED WALLPAPER = "$wallpaper

dbus-send --session --dest=org.kde.plasmashell --type=method_call /PlasmaShell org.kde.PlasmaShell.evaluateScript 'string:
var Desktops = desktops();
for (i=0;i<Desktops.length;i++) {
        d = Desktops[i];
        d.wallpaperPlugin = "org.kde.image";
        d.currentConfigGroup = Array("Wallpaper",
                                    "org.kde.image",
                                    "General");
        d.writeConfig("Image", "file://'''$location'''/'${wallpaper}'");
}'
sleep $sleeptime
#done;
}

function getbinalias
{
  grep -i -r ^alias  ~/bin
}

function getfunctions
{
 echo Functions in bin folder:
 grep ^function ~/bin/* | awk '{print $2}' | sort;
}

function getprogramdefinitions
{
 cat ~/bin/programdefinitions | fzf;
}

function getfunction
{
if [ ! "$#" -gt 0 ]; then read -r -p "Did you mean getfunctions? Enter a word to search bin for a function: " varWord; fi ;
  if [ ! "$#" -eq 0 ]; then varWord=$1; fi
  cd ~/bin/ || exit
  a=$(grep -R -i ^function ~/bin/*  | awk '{print $2}' | grep -i "$varWord");
  for word in $a; do echo "$word"; done;
}

function getcommand
{ declare -F | grep -v _ | awk '{print $3}' | fzf; }

function findcommand
{ grep "$1" ~/bin/* || echo 'Nothing found'; }

function listcommand
{ grep ^function ~/bin/*; }


