#!/bin/bash


function ShortcutsTerminal
{
echo "
ctrl-( split right
ctrl-) split below
ctrl-shift-left focus left
ctrl-shift-right focus right
"
}
alias TerminalShortcuts="ShortcutsTerminal"

function ShortcutsGuake
{
echo "
 - Toggle Guake visibility:
   F12

 - Toggle fullscreen mode:
   F11

 - Open a new tab:
   Ctrl+Shift+T

 - Close the terminal:
   Super+X

 - Go to the previous tab:
   Ctrl+PageUp

 - Search the selected text in the browser:
   Shift+Ctrl+L
"
}

function ShortcutsKeepass
{
  # https://keepass.info/help/kb/keyb_shortcuts.
echo "
ctrl-b username
ctrl-c password
ctrl-u url
ctrl-v autotype
ctrl-w close database" | dmenu -l 5;
}


function ShortcutsPhoto
{
echo "
Rotate [,]
ctrl-d Delete
ctrl-r Rename
space  Next picture
ctrl-space Toggle next picture
file:///usr/share/doc/geeqie/html/GuideReferenceKeyboardShortcuts.html
"
}

function HelpVim
{
 vim /home/adrian/.vim/plugged/vimwiki/doc/vimwiki.txt;
}

function ShortcutsVim
{
  echo "ctrl-t terminal
  getvimhelp" | dmenu -l 2;

}


function ShortcutsBrave
{
echo "
Address bar      ctrl-e
Tab next         ctrl-page-up
Tab previous     ctrl-page-down
Tab new          ctrl-t
Close window     ctrl-w
Find next match  ctrl-g
Scroll up        shift-space
Scroll down      space
Search bookmarks :b
Search history   :h" | dmenu -l 10 ;
}
alias BraveShortcuts=ShortcutsBrave

function ShortcutsCmd
{
echo "Konsole
Focus above        ctrl-shift-up
Keyboard shortcuts ctrl-alt-,
Konsole            ctrl-alt-t
Menu               ctrl-shift-f10
New Tab            ctrl-shift-t
New Window         ctrl-shift-n
Quit               ctrl-shift-q
Split left/right   ctrl-(
Split below        ctrl-)" | dmenu -l 10 ;
}

function ShortcutsWindows
{
echo "Kwin

meta-f Fullscreen
meta-m Minimize
meta-q Close
meta-down Move Window to Bottom
meta-left Move Window to Left
meta-right Move Window to Right
meta-up Move Window Up
meta-ctrl-Left Window to Bottom Left
meta-ctrl-Right Window to Bottom Right
meta-shift-Left Window to top Left
meta-shift-Right Window to top right
meta-k focus to window above
meta-j focus to window below
meta-h focus to window left
meta-l focus to window right
ctrl-meta-h move window left
ctrl-meta-j move window down
ctrl-meta-k move window up
ctrl-meta-l move window right
Darkmode toggle mod-ctrl-d
Rotate windows alt-tab
Window overview mod-w
Window menu alt-space" | dmenu -l 20;
}

function ShortcutsDwm
{
  echo "Alt+Shift+Enter - Launch xterm
  Alt+Shift+C   - Kill a client (a window, if you must insist)
  Alt+Enter     - Rotate clients
  Alt+M         - Monocle (Maximized) Window
  Alt+t         - Tiled Window
  Alt+f         - Floating Window
  Alt+t         - Switch to tile layout
  Alt+m         - Switch to monocle layout
  Alt+f         - Switch to floating layout
  Alt+b         - Show/hide bar
  Alt+p         - Launch dmenu
  Alt+j         - Shift focus left
  Alt+k         - Shift focus right
  Alt+Enter     - Move focused window
  Alt+h         - Change ratio
  Alt+l         - Change ratio
  Alt+[num]     - Switch to tag [num]
  Alt+Shift+Q   - Quit dwm" | dmenu -l 17 ;
}

function ShortcutsTmux
{
#vim -c BTags "$HOME/vimwiki/tmux.md"

cd "$HOME/vimwiki/" || exit

#  file_line=$(rg "^#" tmux.md -S --no-ignore --no-heading --column --color ansi  |\
#        fzf --no-sort --ansi --border --delimiter=: \
#        --preview 'bat --color always {} -n -H {3} -r {2}:+20') 
#        #--preview-window 'top,80%,border-bottom')
#
#        file=$(echo "$file_line" | gawk -F: '{print $1}')
#        line=$(echo "$file_line" | gawk -F: '{print $2}')
#    if [[ -n $file ]]; then
#        nvim +"$line" "$file"
#    fi

 file_line=$(rg "^(##+ )+[^##]*" 'tmux.md' -H -i --no-heading --no-ignore --column --color ansi | 
        fzf --ansi --border --border-label 'TmuxNotes' --reverse  --delimiter=: \
        --preview 'bat --color always {1} -n -H {2} -r {2}:+20')
         # {1} -n  -H {2} -r {2}:+20') 
        #--preview-window 'top,80%,border-bottom')

        file=$(echo "$file_line" | gawk -F: '{print $1}')
        line=$(echo "$file_line" | gawk -F: '{print $2}')
    if [[ -n $file ]]; then
        nvim +"$line" "$file"
    fi



#  echo ctrl-b x close window
#  echo ctrl-b % vertical split
#  echo ctrl-b \" horizontal split
#  echo ctrl-b o swap panes
}
alias TmuxNotes=ShortcutsTmux

function wiki
{
 cd ~/vimwiki || exit
}

function HelpIdeas
{
  echo shellcheck # name of script
  echo howdoi;
  echo tldr;
  echo navi '(not installed)';
  echo diff-so-fancy '(not installed)';
  echo getshortcuts;
}

function ShortcutsBashKeybinding
{ echo empty for now; }


function ShortcutsBash
{
  xdg-open https://ss64.com/bash/syntax-keyboard.html
}

function ShortcutsLeadersVim
{
  grep leader ~/.vimrc | grep -vE '^"'                                                                    
}

function ShortcutsBashCommands
{
  grep -i bind ~/.bashrc ;
}

function ShortcutsAliasesBashrc
{
  grep -i alias ~/.bashrc ;
}
