#!/bin/bash


function testNote {
notefilename="~/Documents/test.md"


if [ ! -f $noteFilename ];
    then
    echo "# Notes for $(date +%Y-%m-%d)" > $notefilename
    fi


    nvim -c "norm Go" \
    -c "norm Go## $(date +%H:%M)"\
    -c "norm G20" \
    -c "norm zz" \
    -c "startinsert" $notefilename
}
