#!/bin/bash

function TroubleShootTroubleshooting 
{ xdg-open https://www.shellcheck.net/; }




function TroublshootWhere 
{
  shopt -s extdebug ;
  declare -F "$1" ;
  # to turn off extdebug: 
  shopt -u extdebug ;
}
alias where=TroublshootWhere

function TroubleShootGetProcess
{ 
  if [ ! "$#" -gt 0 ]; then read -r -p "Enter a process to search: " var; fi ;
  if [ ! "$#" -eq 0 ]; then var=$1; fi
    #[ -z "$var" ] && echo "Enter an argument or did you mean getprocesses? " ||

  ps aux | pgrep -i "$var" | pgrep -v grep; 
}
alias getprocess=TroubleshootGetProcess

function TroubleShootGetProcesses
{
 btop || (command -v btop >/dev/null 2>&1 || { echo >&2 "Btop required but not installed. Aborting."; exit 1; })
}
alias getprocesses=TroubleShootGetProcesses

